### ISSUE TITLE
-execdir fails for the root directory

### ISSUE THREAD

**Issue by tavianator** [uutils/findutils#23]
```
$ ./target/debug/find -maxdepth 0 -execdir echo '{}' \;
Failed to run echo: No such file or directory (os error 2)
```

**Comment by mcharsley** [comment]
Should be now fixed by 8c7cf29e697b8efb0f8f73c5c5fa36bf52752ced

Thanks for the bug report

**Comment by tavianator** [comment]
Thanks!  Looks like this related command line is still broken, should I open a new bug?

```
$ ./target/debug/find src -maxdepth 0 -execdir echo '{}' \;
Failed to run echo: No such file or directory (os error 2)
```

**Comment by mcharsley** [comment]
I'll re-open this one
